services:
  database:
    image: postgres:16
    container_name: nest_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5433"

  s3:
    image: minio/minio:latest
    container_name: nest_s3
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT}:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nest_redis-commander
    environment:
      REDIS_HOSTS: local:${REDIS_HOST}:${REDIS_HOST}
    ports:
      - "8081:8081"
    depends_on:
      - redis

  server:
    build:
      dockerfile: Dockerfile
    container_name: nest_server
    restart: on-failure
    ports:
      - "${NEST_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - s3
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
  s3_data: